=== rvsjoen/joomla-manifests/access.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.joomla.org/access" xmlns:tns="http://www.joomla.org/access"
	elementFormDefault="qualified">

	<complexType name="AccessType">
		<sequence>
			<element name="section" type="tns:SectionType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
		<attribute name="component" type="string"></attribute>
	</complexType>

	<complexType name="ActionType">
		<attribute name="name" type="string"></attribute>
		<attribute name="title" type="string"></attribute>
		<attribute name="description" type="string"></attribute>
	</complexType>

	<complexType name="SectionType">
		<sequence>
			<element name="action" type="tns:ActionType" maxOccurs="unbounded" minOccurs="0"></element>
		</sequence>
		<attribute name="name" type="string"></attribute>
	</complexType>

	<element name="access" type="tns:AccessType"></element>
</schema>

=== rvsjoen/joomla-manifests/access_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<access 
	xmlns="http://www.joomla.org/access" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.joomla.org/access access.xsd"
	component="com_helloworld">
	<section name="component">
		<action name="core.admin" 		title="JACTION_ADMIN" 		description="JACTION_ADMIN_COMPONENT_DESC"/>
		<action name="core.manage" 		title="JACTION_MANAGE" 		description="JACTION_MANAGE_COMPONENT_DESC"/>
		<action name="core.create" 		title="JACTION_CREATE" 		description="JACTION_CREATE_COMPONENT_DESC"/>
		<action name="core.delete" 		title="JACTION_DELETE" 		description="JACTION_DELETE_COMPONENT_DESC"/>
		<action name="core.edit" 		title="JACTION_EDIT" 		description="JACTION_EDIT_COMPONENT_DESC"/>
		<action name="core.edit.own"	title="JACTION_EDIT_OWN" 	description="JACTION_EDIT_OWN_COMPONENT_DESC"/>
		<action name="core.edit.state" 	title="JACTION_EDIT_STATE" 	description="JACTION_EDIT_STATE_COMPONENT_DESC"/>
	</section>
	<section name="category">
		<action name="core.create" 		title="JACTION_CREATE" 		description="COM_CATEGORY_ACCESS_CREATE_DESC"/>
		<action name="core.delete" 		title="JACTION_DELETE" 		description="COM_CATEGORY_ACCESS_DELETE_DESC"/>
		<action name="core.edit" 		title="JACTION_EDIT" 		description="COM_CATEGORY_ACCESS_EDIT_DESC"/>
		<action name="core.edit.state" 	title="JACTION_EDIT_STATE" 	description="COM_CATEGORY_ACCESS_EDITSTATE_DESC"/>
	</section>
</access>
