=== rvsjoen/joomla-manifests/extension-template.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
	xmlns="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.example.org/extension-template" 
	xmlns:tns="http://www.example.org/extension-template" 
	elementFormDefault="qualified">
	<element name="extension" type="tns:ExtensionType"></element>
    <complexType name="ExtensionType">
    	<all>
    		<element name="name" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="creationDate" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="author" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="authorEmail" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="authorUrl" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="copyright" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="license" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="version" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="description" type="string" maxOccurs="1" minOccurs="0"></element>
    		<element name="files" type="tns:FilesType" maxOccurs="1" minOccurs="0"></element>
    	</all>
    	<attribute name="type" type="string" use="required" fixed="template"></attribute>
    	<attribute name="version" type="string"></attribute>
    	<attribute name="method" default="install">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="install"></enumeration>
    				<enumeration value="upgrade"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    	<attribute name="client" default="site">
    		<simpleType>
    			<restriction base="string">
    				<enumeration value="site"></enumeration>
    				<enumeration value="administrator"></enumeration>
    			</restriction>
    		</simpleType>
    	</attribute>
    </complexType>
    <complexType name="FilesType">
    	<sequence>
    		<element name="folder" type="tns:FolderType" maxOccurs="unbounded" minOccurs="0" ></element>
    		<element name="filename" type="tns:FilenameType" maxOccurs="unbounded" minOccurs="0"></element>
    	</sequence>
    	<attribute name="folder" type="string"></attribute>
    </complexType>
	<simpleType name="FilenameType">
    	<restriction base="string"></restriction>
    </simpleType>
    <simpleType name="FolderType">
    	<restriction base="string"></restriction>
    </simpleType>
</schema>

=== rvsjoen/joomla-manifests/extension-template_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<extension 
	xmlns="http://www.joomla.org" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.joomla.org extension-template.xsd "
	method="upgrade"
	client="site"
	version="1.6"
	type="template"
>
  	<!-- All of these are optional, zero or one instances, with no formatting constraints -->
	<name>COM_HELLWORLD</name>
	<creationDate>July 2010</creationDate>
	<author>John Doe</author>
	<authorEmail>john@doe.com</authorEmail>
	<authorUrl>http://www.john.doe.com</authorUrl>
	<copyright>John Doe</copyright>
	<license>GNU/GPL</license>
	<description><![CDATA[TPL_HELLOWORLD_XML_DESCRIPTION]]></description>
	<version>1.0</version>
  
	<files>
		<folder>css</folder>
		<folder>html</folder>
		<folder>images</folder>
		<folder>js</folder>
		<filename>index.php</filename>
		<filename>templateDetails.xml</filename>
	</files>
</extension>
